config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  get 'events/index'
  get 'events/new'
  get 'events/create'
  get 'events/delete'

  root "events#index"

  devise_for :users
  resources :users, only: [:show]
  resources :events
  resources :attendances
  resources :invitations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :attendances, foreign_key: "attended_event_id"
  has_many :attendees, through: :attendances

  has_many :invitations, foreign_key: "invited_event_id"
  has_many :invited_users, through: :invitations
  
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :location, presence: true

  scope :future_events, -> { where("date >= ?", Date.today) }
  scope :past_events, -> { where("date < ?", Date.today) }

  def self.future
    where("date >= ?", Date.today)
  end

  def self.past
    where("date < ?", Date.today)
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_user, class_name: "User"
  belongs_to :invited_event, class_name: "Event"

  def self.get_invited_user(email)
    user = User.find_by("email = ?", email)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: :creator_id

  has_many :attendances, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances

  has_many :invitations, foreign_key: "invited_user_id"
  has_many :invited_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @event = Event.find(attendance_params)
  end

  def show
    @attendance = current_user.attendances
  end

  def index
    @attendance = current_user.attendances
  end

  def create
    @attendance = Attendance.create(attendance_params)
    @attendance.save
    flash[:notice] = "You have successfully registered for the event."
    redirect_to root_path
  end

  def destroy
    @attendance = Attendance.find_by(attended_event_id: params[:id]).destroy
    
    flash[:notice] = "You have successfully withdrew from this event."
    redirect_to attendances_path
  end


  private

  def attendance_params
    params.require(:attendance).permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash.now[:notice] = "Your event has been successfully created."
      redirect_to event_path(@event)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash.now[:notice] = "Your event has been successfully updated."
      redirect_to event_path(@event)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Your event was successfully destroyed."
    redirect_to user_show_path
  end


  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :creator_id)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_user, only: [:create]
  before_action :set_event, only: [:create]
  before_action :check_if_invitation_exists, only: [:create]

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = @user.invitations.build(invited_user_id: @user.id, invited_event_id: @event.id)
    if @invitation.save
      flash[:notice] = "Your invitation has successfully been sent"
      redirect_to new_invitation_path(invitation: {invited_event_id: @event.id})
    else
      render :action => "new", status: :unprocessable_entity
    end
  end

  private

  def invitation_params
    params.permit(:invited_user_id, :invited_event_id, :invited_user_email)
  end

  def set_event
    @event = Event.find(params[:invitation][:invited_event_id])
  end

  def set_user
    @user = User.find_by(email: params[:invitation][:invited_user_email])
  end

  def check_if_invitation_exists
    if @user.nil?
      flash[:notice] = "There is no user with this email."
      redirect_to new_invitation_path(invitation: {invited_event_id: @event.id})
    elsif Invitation.where(invited_event_id: @event.id, invited_user_id: @user.id).exists?
      flash[:notice] = "This user has already received an invite."
      redirect_to new_invitation_path(invitation: {invited_event_id: @event.id})
    end
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendances/_event.html.erb
<div class="mb-3 w-50">
  <%= link_to event.title, event %><br>
  <%= event.description %><br>
  <%= event.location %><br>
  <%= event.date %><br>
  <%= button_to "Delete", attendance_path(event), method: :delete, class: "text-danger"%>
</div>

app/views/attendances/_event_index.html.erb
<div class="d-flex justify-content-between m-5">
  <div class="w-50">
    <h2>Future Events</h2>
      <% current_user.attended_events.each do |event| %>
        <% if event.date.after?(Date.today) %>

          <%= render  partial: "event", locals: {event: event} %>

        <% end %>
      <% end %>
  </div>

  <div class="w-50">
    <h2>Past Events</h2>
      <% current_user.attended_events.each do |event| %>
        <% if event.date.before?(Date.today) %>
        
          <%= render partial: "event", locals: {event: event} %>

        <% end %>
      <% end %>
  </div>
</div>

app/views/attendances/index.html.erb
<h1 class="mt-5 mx-5">Events You're Attending!</h1>

<%= render "event_index" %>

<% if current_user.attended_events.empty? %>
  <div>You're not signed up for any events yet!</div>
<% end %>

app/views/attendances/show.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1>Events You're Attending!</h1>

<% if @attendance.any? %>
  <% @attendance.each do |event| %>
    <%= link_to event.title, event %><br>
    <%= event.description %><br>
    <%= event.location %><br>
    <%= event.date %><br>
  <% end %>
<% else %>
  <div>You're not signed up for any events yet!</div>
<% end %>

app/views/events/_event.html.erb
<div class="mb-3 w-50">
  <%= link_to event.title, event %><br>
  <%= event.description %><br>
  <%= event.location %><br>
  <%= event.date %><br>
</div>

app/views/events/_event_index.html.erb
<div class="d-flex justify-content-between m-5">
  <div class="w-50">
    <h2>Future Events</h2>
      <% Event.future_events.each do |event| %>
        <%= render  partial: "event", locals: {event: event} %>
      <% end %>
  </div>

  <div class="w-50">
    <h2>Past Events</h2>
      <% Event.past_events.each do |event| %>
        <%= render partial: "event", locals: {event: event} %>
      <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
    <div class="card-body">
      <div class="mb-1">
        <%= form.label :title, "Title:", class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :description, class: "form-label"%>
        <%= form.text_area :description, class: "form-control", size: "70x5", placeholder: "Describe your event here..." %>
      </div>
      <div class="mb-3">
        <%= form.label :location, class: "form-label"%>
        <%= form.text_field :location, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :date, class: "form-label"%>
        <%= form.date_field :date, class: "form-control" %>
      </div>
      <div class="d-grid gap-2">
        <%= form.submit "Post", class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<%= render "layouts/flash" %>

<% if @event.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being updated:</h2>

    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card mx-auto mt-5 w-50">
  <div class="card-header">
    Edit Event
  </div>
  <%= render "form" %>
</div>

app/views/events/index.html.erb
<h1 class="mt-5 mx-5">Get to an event!</h1>

<% if @events.any? %>
  <%= render "event_index" %>
<% else %>
  <div>There are no events yet!</div>
<% end %>

app/views/events/new.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<div class="card mx-auto mt-5 w-50">
  <div class="card-header">
    New Event
  </div>
  <%= form_with model: @event do |form| %>
    <div class="card-body">
      <div class="mb-1">
        <%= form.label :title, "Title:", class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :description, class: "form-label"%>
        <%= form.text_area :description, class: "form-control", size: "70x5", placeholder: "Describe your event here..." %>
      </div>
      <div class="mb-3">
        <%= form.label :location, class: "form-label"%>
        <%= form.text_field :location, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :date, class: "form-label"%>
        <%= form.date_field :date, class: "form-control" %>
      </div>
      <div class="d-grid gap-2">
      <%= form.submit "Post", class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<h1>Event:</h1>
<%= @event.title %><br>
<%= @event.description %><br>
<%= @event.location %><br>
<%= @event.date %><br>
<%= link_to "Back", root_path %><br>
<% if current_user && @event.creator != current_user && !@event.attendees.include?(current_user) && @event.invited_users.include?(current_user) %>
  <%= button_to "Attend this event", attendances_path(attendance: { attended_event_id: @event.id, attendee_id: current_user.id }) %>
<% elsif @event.creator == current_user %>
  <div class="text-success">This is your event!</div>
<% elsif !@event.invited_users.include?(current_user) %>
  <div class="text-warning">You have not been invited to this event</div>
<% else %>
  <div class="text-success">You have registered for this event.</div>
<% end %>
<br>

<h1>Attending this event</h1>
<% if @event.attendees.any? %>
  <% @event.attendees.each do |attendee| %>
    <%= attendee.email %><br>
  <% end %>
<% end %>

app/views/invitations/_form.html.erb
<%= form_with model: @invitation, data: { turbo: false } do |form| %>
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :invitation, class: "form-label"%>
        <%= form.email_field :invited_user_email, class: "form-control" %>
        <%= form.hidden_field :invited_event_id, :value => params[:invitation][:invited_event_id] %>
      </div>
      <div class="d-grid gap-2 mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
      <div class="d-grid gap-2">
        <%= link_to "Back to your events", user_show_path, class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/new.html.erb
<div class="card mx-auto mt-5 w-50">
  <div class="card-header">
    New Invitation
  </div>
  <%= render "form" %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-primary" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Private Events", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Events You're Attending", attendances_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Events You're Hosting", user_show_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Event", new_event_path, class: "nav-link text-success" %>
          </li>
        <% end %>
      </ul>
      <% if !user_signed_in? %>
        <li class="nav-item d-flex px-3">
          <%= link_to "New User", new_user_registration_path, class: "btn btn-outline-success" %>
        </li>
        <li class="nav-item d-flex">
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-success" %>
        </li>
      <% else %>
        <li class="nav-item d-flex">
          <div>Signed in as: <%= current_user.email %></div>
        </li>
        <li class="nav-item d-flex">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>
        </li>
      <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/notice" %>
    <%= yield %>
  </body>
</html>

app/views/user/_event.html.erb
<div class="mb-3 w-50">
  <%= link_to event.title, event %><br>
  <%= event.description %><br>
  <%= event.location %><br>
  <%= event.date %><br>
  <div class="d-flex ">
    <%= button_to "Delete", event_path(event), method: :delete, class: "btn btn-danger m-3" %>
    <%= link_to "Edit", edit_event_path(event), class: "btn btn-primary m-3" %>
    <%= link_to "Send invitation", new_invitation_path(invitation: { invited_event_id: event.id} ), class: "btn btn-primary m-3" %>
  </div>
</div>

app/views/user/show.html.erb
<div class="m-5">
  <h1 class="mb-5">Events you're hosting</h1>
  <% if current_user.events.any? %>
    <% current_user.events.each do |event| %>
      <%= render partial: "event", locals: {event: event} %>
    <% end %>
  <% end %>
</div>